### ISSUE TITLE
连续多次发送645数据时，极大概率出现check code error!，因为接收数据data[0]和data[1]均为0x68

### ISSUE THREAD

**Issue by rance110** [WKJay/DLT645#5]
![Uploading Q8_UAP2[$YW$APX(Z3X]E8Y.png…]()

**Comment by WKJay** [comment]
连续多次发具体是指什么意思？

**Comment by rance110** [comment]
> 连续多次发具体是指什么意思？

就是以很快的频率发送两次数据，比如68 03 00 00 00 00 00 68 91 07 33 34 34 35 33 33 33 D4 16，但是会发现发送的数据变成了68 68 03 00 00 00 00 00 68 91 07 33 34 34 35 33 33 33 D4 16，多了一位68。不过目前已解决了，是串口中断没处理好，我这边用的freertos，修改一下代码就好了。

**Comment by WKJay** [comment]
好的
